services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
    timescale-data:
